import { LevelId } from "@/types";

export interface ContextSentence {
  id: string;
  kannada: string; // The full sentence in Kannada script
  english: string; // The English translation
  romanization: string; // The romanized version of the sentence
  blankWord: string; // The word to blank out in the exercise
  minLevel: LevelId; // Minimum curriculum level to show this sentence
}

export const CONTEXT_SENTENCES: ContextSentence[] = [
  {
    id: "sent_1",
    kannada: "ನಾನು ಮನೆಗೆ ಹೋಗುತ್ತೇನೆ",
    english: "I am going home.",
    romanization: "naanu manege hoogutteene",
    blankWord: "ನಾನು",
    minLevel: 5,
  },
  {
    id: "sent_2",
    kannada: "ನೀನು ನೀರು ಕುಡಿ",
    english: "You, drink water.",
    romanization: "neenu neeru kudi",
    blankWord: "ನೀರು",
    minLevel: 8,
  },
  {
    id: "sent_3",
    kannada: "ಅವನು ಹಣ್ಣು ತಿನ್ನುತ್ತಾನೆ",
    english: "He is eating fruit.",
    romanization: "avanu hannu tinnuttaane",
    blankWord: "ಹಣ್ಣು",
    minLevel: 8,
  },
  {
    id: "sent_4",
    kannada: "ನನ್ನ ಬೆಕ್ಕು ಬಿಳಿ ಬಣ್ಣ",
    english: "My cat is white.",
    romanization: "nanna bekku bili banna",
    blankWord: "ಬೆಕ್ಕು",
    minLevel: 8,
  },
  {
    id: "sent_5",
    kannada: "ಮನೆ ಬಾಗಿಲು ದೊಡ್ಡದು",
    english: "The house door is big.",
    romanization: "mane baagilu doddadu",
    blankWord: "ಬಾಗಿಲು",
    minLevel: 8,
  },
  {
    id: "sent_6",
    kannada: "ಅಮ್ಮ ಅಡುಗೆ ಮಾಡುತ್ತಾರೆ",
    english: "Mother is cooking.",
    romanization: "amma aduge maaduttaare",
    blankWord: "ಅಡುಗೆ",
    minLevel: 8,
  },
  {
    id: "sent_7",
    kannada: "ಅಪ್ಪ ಪುಸ್ತಕ ಓದುತ್ತಾರೆ",
    english: "Father is reading a book.",
    romanization: "appa pustaka ooduttaare",
    blankWord: "ಪುಸ್ತಕ",
    minLevel: 5,
  },
  {
    id: "sent_8",
    kannada: "ಹಕ್ಕಿ ಆಕಾಶದಲ್ಲಿ ಹಾರುತ್ತದೆ",
    english: "The bird flies in the sky.",
    romanization: "hakki aakaashadalli haaruttade",
    blankWord: "ಆಕಾಶ",
    minLevel: 9,
  },
  {
    id: "sent_9",
    kannada: "ನದಿ ನೀರು ತಂಪು",
    english: "The river water is cool.",
    romanization: "nadi neeru tampu",
    blankWord: "ತಂಪು",
    minLevel: 6,
  },
  {
    id: "sent_10",
    kannada: "ವಾರಕ್ಕೆ ಏಳು ದಿನಗಳು",
    english: "Seven days in a week.",
    romanization: "vaarakke aelu dinagalu",
    blankWord: "ವಾರ",
    minLevel: 8,
  },
  {
    id: "sent_11",
    kannada: "ನನಗೆ ಕಾಫಿ ಬೇಕು",
    english: "I want coffee.",
    romanization: "nanage kaafi baeku",
    blankWord: "ಕಾಫಿ",
    minLevel: 7,
  },
  {
    id: "sent_12",
    kannada: "ಅಕ್ಕ ಶಾಲೆಗೆ ಹೋಗುತ್ತಾಳೆ",
    english: "Elder sister is going to school.",
    romanization: "akka shaalege hooguttaale",
    blankWord: "ಶಾಲೆ",
    minLevel: 9,
  },
  {
    id: "sent_13",
    kannada: "ಮೋಡದಿಂದ ಮಳೆ ಬರುತ್ತದೆ",
    english: "Rain comes from clouds.",
    romanization: "moodadinda male baruttade",
    blankWord: "ಮಳೆ",
    minLevel: 8,
  },
  {
    id: "sent_14",
    kannada: "ಗಿಡದ ಎಲೆ ಹಸಿರು ಬಣ್ಣ",
    english: "The plant's leaf is green.",
    romanization: "gidada ele hasiru banna",
    blankWord: "ಎಲೆ",
    minLevel: 8,
  },
  {
    id: "sent_15",
    kannada: "ಹುಲಿ ಕಾಡಿನಲ್ಲಿ ವಾಸಿಸುತ್ತದೆ",
    english: "The tiger lives in the forest.",
    romanization: "huli kaadinalli vaasisuttade",
    blankWord: "ಕಾಡು",
    minLevel: 8,
  },
  {
    id: "sent_16",
    kannada: "ಅವಳು ಹಾಡು ಹಾಡುತ್ತಾಳೆ",
    english: "She is singing a song.",
    romanization: "avalu haadu haaduttaale",
    blankWord: "ಹಾಡು",
    minLevel: 8,
  },
  {
    id: "sent_17",
    kannada: "ಅಣ್ಣ ಕೆಲಸ ಮಾಡುತ್ತಾನೆ",
    english: "Elder brother is working.",
    romanization: "anna kelasa maaduttaane",
    blankWord: "ಕೆಲಸ",
    minLevel: 8,
  },
  {
    id: "sent_18",
    kannada: "ಸಮುದ್ರದಲ್ಲಿ ಮೀನು ಇರುತ್ತದೆ",
    english: "Fish live in the ocean.",
    romanization: "samudradalli meenu iruttade",
    blankWord: "ಮೀನು",
    minLevel: 5,
  },
  {
    id: "sent_19",
    kannada: "ಮಗುವಿನ ನಗು ಕಮಲದ ಹಾಗೆ",
    english: "A child's smile is like a lotus.",
    romanization: "maguvina nagu kamalada haage",
    blankWord: "ನಗು",
    minLevel: 4,
  },
  {
    id: "sent_20",
    kannada: "ಸೂರ್ಯ ಬೆಳಿಗ್ಗೆ ಬರುತ್ತಾನೆ",
    english: "The sun comes in the morning.",
    romanization: "suurya beligge baruttaane",
    blankWord: "ಸೂರ್ಯ",
    minLevel: 5,
  },
  {
    id: "sent_21",
    kannada: "ರಾಜ ದೊಡ್ಡ ಆನೆ ಮೇಲೆ ಕುಳಿತನು",
    english: "The king sat on a big elephant.",
    romanization: "raaja dodda aane maele kulitanu",
    blankWord: "ಆನೆ",
    minLevel: 8,
  },
  {
    id: "sent_22",
    kannada: "ದಯವಿಟ್ಟು ಪುಸ್ತಕ ಹಿಡಿ",
    english: "Please hold the book.",
    romanization: "dayavittu pustaka hidi",
    blankWord: "ಹಿಡಿ",
    minLevel: 8,
  },
  {
    id: "sent_23",
    kannada: "ರಾತ್ರಿ ಸಮಯದಲ್ಲಿ ಚಂದ್ರ ಬರುತ್ತಾನೆ",
    english: "The moon comes during the night.",
    romanization: "raatri samayadalli chandra baruttaane",
    blankWord: "ಚಂದ್ರ",
    minLevel: 6,
  },
  {
    id: "sent_24",
    kannada: "ಹಣ್ಣು ತುಂಬಾ ಸಿಹಿ",
    english: "The fruit is very sweet.",
    romanization: "hannu tumba sihi",
    blankWord: "ಸಿಹಿ",
    minLevel: 8,
  },
  {
    id: "sent_25",
    kannada: "ನಮ್ಮ ದೇಶ ಭಾರತ",
    english: "Our country is India.",
    romanization: "namma desha bhaarata",
    blankWord: "ಭಾರತ",
    minLevel: 7,
  },
  {
    id: "sent_26",
    kannada: "ಧನ್ಯವಾದ ಹೇಳು",
    english: "Say thank you.",
    romanization: "dhanyavaada haelu",
    blankWord: "ಧನ್ಯವಾದ",
    minLevel: 9,
  },
  {
    id: "sent_27",
    kannada: "ಅಮ್ಮ ಸೀರೆ ಉಟ್ಟಿದ್ದಾರೆ",
    english: "Mother is wearing a saree.",
    romanization: "amma seere uTTiddaare",
    blankWord: "ಸೀರೆ",
    minLevel: 5,
  },
  {
    id: "sent_28",
    kannada: "ನನಗೆ ಒಂದು ಸೇಬು ಬೇಕು",
    english: "I want one apple.",
    romanization: "nanage ondu sebu baeku",
    blankWord: "ಒಂದು",
    minLevel: 6,
  },
  {
    id: "sent_29",
    kannada: "ಅಣ್ಣನಿಗೆ ಕೆಲಸ ಇದೆ",
    english: "Brother has work.",
    romanization: "annanige kelasa ide",
    blankWord: "ಕೆಲಸ",
    minLevel: 5,
  },
  {
    id: "sent_30",
    kannada: "ಅಮ್ಮನ ನಗು ಮನಸ್ಸಿಗೆ ಸಂತೋಷ",
    english: "Mother's smile is happiness to the heart.",
    romanization: "ammana nagu manassige santosha",
    blankWord: "ಸಂತೋಷ",
    minLevel: 9,
  },
];
